# Generated by Django 6.0.3 on 2026-03-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_boardcolumn_tag_alter_event_options_event_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcolumn',
            name='color',
            field=models.CharField(default='#333333', max_length=50),
        ),
    ]
