# Generated by Django 6.0.3 on 2026-03-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('cover_image', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('to_read', 'Por Leer'), ('reading', 'Leyendo'), ('read', 'Leído'), ('dropped', 'Abandonado')], default='to_read', max_length=20)),
                ('rating', models.FloatField(default=0.0)),
                ('synopsis', models.TextField(blank=True)),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
