# Generated by Django 6.0.3 on 2026-03-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
